config/routes.rb
Rails.application.routes.draw do  
  root 'store#index', as: 'store_index'
  get 'admin/home' => 'admin#home', as: 'admin'

  resources :orders

  resources :products do
    get :who_bought, on: :member
  end

  resources :line_items do
    delete :decrement, on: :member
  end

  resources :carts
  resources :users do
    get :edit_password, on: :member
    put :password_update, on: :member, as: "update_password"
  end

  controller :session do
    get "login" => :new
    post "login" => :create
    delete "logout" => :logout
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_destroy :ensure_an_admin_remains

  has_secure_password

  validates :username, presence: true, uniqueness: true

  class Error < StandardError
  end

  private

  def ensure_an_admin_remains
    if User.count == 0
      raise Error.new("Cant delete last user")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize
  before_action :set_user, only: [:edit, :update, :destroy, :edit_password, :password_update]

  def index
    @users = User.order(:username)
  end

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_path, notice: "#{@user.username} was successfully created" }
        format.json { render json: @user, status: :created }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def edit_password
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "User#{@user.id} username was successfully updated to #{@user.username}" }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def password_update
    respond_to do |format|
      if @user.authenticate(password_params[:current_password])
        @user.update(password: password_params[:new_password])
        format.html { redirect_to users_path, notice: "Password for user#{@user.id} was changed" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to edit_password_user_path, notice: "Current password not provided or incorrect" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    begin
      respond_to do |format|
        if @user&.destroy
          format.html { redirect_to users_path, notice: "User has been successfully deleted" }
          format.json { head :no_content }
        else
          format.html { redirect_to users_path, notice: "User cannot be found" }
          format.json { render json: "User cannot be found", status: 404 }
        end
      end
    rescue User::Error => exception
      redirect_to users_url, notice: exception.message
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    @user = nil
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def password_params
    params.require(:user).permit(:current_password, :new_password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.present? && @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
      prohibited this product from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, size: 20 %>
  </div>

  <br/>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, size: 20  %>
  </div>

  <br/>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password, id: :user_password_confirmation, size: 20  %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit %>
  </div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<% if @user.present? && @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
      prohibited this product from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%= form_with model: @user, local: true do |form| %>
  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, size: 20 %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>



<%= link_to 'Back', users_path %>

app/views/users/edit_password.html.erb
<h1>Edit Password</h1>

<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>


<%= form_with model: @user, url: update_password_user_path(@user), method: :put, local: true do |form| %>
  <div class="field">
    <%= form.label :current_password %>
    <%= form.text_field :current_password, size: 20 %>
  </div>

  <div class="field">
    <%= form.label :new_password %>
    <%= form.text_field :new_password, size: 20 %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit "Update Password" %>
  </div>
<% end %>



<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h2>Users</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Edit Password', edit_password_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with model: @user, local: true do |form| %>
  <%= render 'form', form: form  %>
<% end %>

<%= link_to 'Back', users_path %>