config/routes.rb
Rails.application.routes.draw do  
  root 'store#index', as: 'store_index'
  get 'admin/home' => 'admin#home', as: 'admin'

  resources :orders

  resources :products do
    get :who_bought, on: :member
  end

  resources :line_items do
    delete :decrement, on: :member
  end

  resources :carts
  resources :users do
    get :edit_password, on: :member
    put :password_update, on: :member, as: "update_password"
  end

  controller :session do
    get "login" => :new
    post "login" => :create
    delete "logout" => :logout
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  image_url   :string
#  price       :decimal(8, 2)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Product < ApplicationRecord
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true
  validates_length_of :title, :minimum => 10, :too_short => "can't be less than 10 characters"
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  has_many :line_items
  has_many :orders, through: :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart
  
  before_action :authorize
  before_action :set_product, only: [:show, :edit, :update, :destroy, :who_bought]
  
  def index
    @products = Product.all.order(:title)
  end

  def new
    @product = Product.new
  end

  def show
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }

        @products = Product.all.order(:title)
        
        ActionCable.server.broadcast 'products',
          { html: render_to_string('store/index', layout: false) }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @product.destroy
        format.html { redirect_to products_path, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to products_path, notice: @product.errors }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def who_bought
    @orders = @product.orders
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.present? && @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %>
      prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10, cols: 60 %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

app/views/products/edit.html.erb
<h1>New Product</h1>

<%= form_with model: @product, url: product_path(@product), method: :patch,  local: true do |form| %>
  <%= render 'form', form: form %>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Products</h1>

<table>
  <tbody>
    <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

        <td class="image">
          <%= image_tag(product.image_url, class: 'list_image') %>
        </td>

        <td class="description">
          <h1><%= product.title %></h1>
          <p>
            <%= truncate(strip_tags(product.description),
                         length: 80) %>
          </p>
        </td>

        <td class="actions">
          <ul>
            <li><%= link_to 'Show', product %></li>
            <li><%= link_to 'Edit', edit_product_path(product) %></li>
            <li>
              <%= link_to 'Destroy',
                           product, 
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %>
            </li>
            <li><%= link_to 'Who Bought', who_bought_product_path(product) %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">
        <%= link_to 'New Product', new_product_path %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_with model: @product, local: true do |form| %>
  <%= render 'form', form: form %>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% unless notice.nil? %>
  <p id="notice"><%= notice %></p>
<% end %>  

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/who_bought.html.erb
<% total = 0 %>

<table>
  <tr> 
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Payment Type</th>
  <tr>

  <% @orders.each do |order| %>
    <% item = order.get_product_item(@product) %>
    <tr>
      <td><%= order.name %></td>
      <td><%= order.address %></td>
      <td><%= order.email %></td>
      <td><%= item.quantity %></td>
      <td><%= item.total_price %></td>
      <% total += item.total_price %>
      <td><%= order.paytype %></td>
    </tr>
  <% end %>
</table>

<br/>
<table>
  <tr>
    <th>Total Revenue</th>
  </tr>
  <tr>
    <td><%= number_to_currency(total) %></td>
  </tr>
</table>