config/routes.rb
Rails.application.routes.draw do  
  root 'store#index', as: 'store_index'
  get 'admin/home' => 'admin#home', as: 'admin'

  resources :orders

  resources :products do
    get :who_bought, on: :member
  end

  resources :line_items do
    delete :decrement, on: :member
  end

  resources :carts
  resources :users do
    get :edit_password, on: :member
    put :password_update, on: :member, as: "update_password"
  end

  controller :session do
    get "login" => :new
    post "login" => :create
    delete "logout" => :logout
  end
end

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id         :bigint           not null, primary key
#  product_id :bigint           not null
#  cart_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quantity   :integer          default(1)
#  order_id   :bigint
#
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart, optional: true

  def total_price
    price = product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart

  before_action :set_cart, only: [:create, :decrement]

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        session[:counter] = 0
        format.html { redirect_to store_index_url }
        format.js { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def decrement
    line_item = LineItem.find(params[:id])

    if line_item.quantity == 1
      redirect_to store_index_url, notice: "Cannot decrement any further"
    else
      respond_to do |format|
        line_item.quantity = line_item.quantity - 1
        line_item.save

        format.js do 
          render  :template => "line_items/create.js.erb", :layout => false
        end

        format.html { redirect_to store_index_url }
      end
      
    end
  end

  def destroy
    line_item = LineItem.find(params[:id])
    title = line_item.product.title

    respond_to do |format|
      if line_item.destroy
        format.html { redirect_to store_index_url, notice: "Your item #{title} has been destroyed" }
        format.json { head :no_content }
      end  
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr class="line-item-highlight">
<% else %>
<tr>
<% end %>
  <td class="quantity"><%= line_item.quantity %></td>
  <td><%= line_item.product.title %></td>
  <td class="price"><%= number_to_currency(line_item.total_price) %></td>
  <td><%= button_to 'Delete Item', line_item,
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
  </td>

  <td><%= button_to 'Decrement', decrement_line_item_url(line_item),
          method: :delete, remote: true %>
  </td>
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s", line_item.quantity, truncate(line_item.product.title, length: 50)) %>

app/views/line_items/create.js.erb
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

notice = document.getElementById("notice")
if (notice) notice.style.display = "none"