config/routes.rb
Rails.application.routes.draw do  
  root 'store#index', as: 'store_index'
  get 'admin/home' => 'admin#home', as: 'admin'

  resources :orders

  resources :products do
    get :who_bought, on: :member
  end

  resources :line_items do
    delete :decrement, on: :member
  end

  resources :carts
  resources :users do
    get :edit_password, on: :member
    put :password_update, on: :member, as: "update_password"
  end

  controller :session do
    get "login" => :new
    post "login" => :create
    delete "logout" => :logout
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakeshop</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="main">
      <%= image_tag 'logo.svg', alt: 'FakeShop' %>
      <h1><%= @page_title %></h1>
    </header>
    <section class="content">
      <nav class="side_nav">
        <div id="cart" class="carts">
          <%= render_if @cart && @cart.line_items.any?, @cart %> 
        </div>
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="/questions">Questions</a></li>
          <li><a href="/news">News</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
        
        <% if session[:user_id] %>
          <nav class="logged_in_or_logged_out">
            <ul>
              <li><%= link_to 'Admin Home', admin_path %></li>
              <li><%= link_to 'Orders',   orders_path %></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users',    users_path %></li>
              <li><%= button_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </nav> 
        <% else %>
          <nav class="logged_in_or_logged_out">
            <ul>
              <li><%= link_to 'login', login_path %></li>
          </nav> 
        <% end %>
      </nav>

      <main class='<%= controller.controller_name %>'>
        <%= yield %>
      </main>
    </section>
  </body>
</html>